notifications:
  email: false
dist: trusty
sudo: required
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
before_script:
 - mkdir build
 - cd build
 - cmake ..
jobs:
  include:
    - stage: Library - Tier 1
      script:
        - make -d Platform
    -
      script:
        - make -d IRender
    -
      script:
        - make -d Types
    - stage: Library - Tier 2
      script:
        - make -d Core
    - stage: Tests
      script:
        - make -d Test-Types
        - ./bin/Test-Types
    - 
      script:
        - make -d Test-Core
        - ./bin/Test-Core
    - stage: Application
      script:
        - make -d Application
