notifications:
  email: false
dist: trusty
sudo: required
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
before_script:
 - mkdir build
 - cd build
 - cmake ..
jobs:
  include:
    - stage: Library
      script:
        - make -f build/Soure/Core/Makefile
    - stage: Test
      script:
        - make -f build/Soure/Test/Core_Test/Makefile
        - ./bin/Test-Core
