notifications:
  email: 
    false
dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
matrix:
  include:
    script:
      - g++ -std=c++1y -c Source/Core/*.cpp
      - ar rcs libCore.a
    script:
      - g++ -std=c++1y -ISource -o run Source/Test/Core_Test/*.cpp liCore.a