notifications:
  email: 
    false
dist: trusty
sudo: required
language:
  - cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
jobs:
  include:
    - stage: Library
      script:
        - cmake Source/Core
	- rm CMakeCache.txt
    - stage: Test
      script:
        - cmake Source/Test/Core_Test
	- rm CMakeCache.txt
        - ./bin/Test-Core
